# fly.toml app configuration file generated for ai-blog-writer on 2023-07-15T16:32:10+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ai-blog-writer"
primary_region = "lhr"

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
